import { type RouteConfig, index, route } from '@react-router/dev/routes';

export default [
  index('routes/home.tsx'),
  route('arm', 'routes/arm.tsx'),
  route('belts', 'routes/belts.tsx'),
  route('chains', 'routes/chains.tsx'),
  route('flywheel', 'routes/flywheel.tsx'),
  route('intake', 'routes/intake.tsx'),
  route('linear', 'routes/linear.tsx'),
  route('motors', 'routes/motors.tsx'),
  route('ratio', 'routes/ratio.tsx'),
  route('gears', 'routes/gears.tsx'),
  route('ratio-finder', 'routes/ratio-finder.tsx'),
  route('privacy', 'routes/privacy.tsx'),
  route('about', 'routes/about.tsx'),
  route('zh', 'routes/zh/home.tsx'),
  route('zh/arm', 'routes/zh/arm.tsx'),
  route('zh/belts', 'routes/zh/belts.tsx'),
  route('zh/chains', 'routes/zh/chains.tsx'),
  route('zh/flywheel', 'routes/zh/flywheel.tsx'),
  route('zh/linear', 'routes/zh/linear.tsx'),
  route('zh/ratio', 'routes/zh/ratio.tsx'),
  route('zh/ratio-finder', 'routes/zh/ratio-finder.tsx'),
  route('dev/error', 'routes/dev.error.tsx'),
] satisfies RouteConfig;
